### ISSUE TITLE
'svn diff -c r'REV' from VCLog

### ISSUE THREAD

**Issue by mrzaus123** [juneedahamed/vc.vim#4]
Hi!

Great work, your plugin is really useful and thanks for your work! There is one thing I can't do so far: while browsing log I'd like to see full diff from selected revision like this:

:VCLog .
r2131 mrzaus123 ...
r1231 mrzaus123 ...
r23 mrzaus123 ...

and select r1231 to execute svn diff -c r1231. 

Is it possible or not implemented? Thanks!

**Comment by juneedahamed** [comment]
Hi,

while the log is displayed you can use the up and down arrow keys to select the required revision then press enter key to bring up the diff 

Juneed

**Comment by juneedahamed** [comment]
Hi

  just realized that there was a period on VCLog the steps I mentioned works for sure for a file not sure for the directory. I am not in front of a computer and wont get access for a few days :( Will respond back as soon as i can but u can still try n see what is the behavior with the mentioned steps. i believe it gives the status/modifications that where committed for selected revision when an enter key is pressed. also note that there is help which shows the short keys

Juneed

**Comment by mrzaus123** [comment]
Hi!

Thanks for very fast reply! When I select rev and hit enter I get list of files, not the diff...
I'd like to see all changes done in a rev selected with VCLog (output of svn diff -c r[REVISION])

**Comment by juneedahamed** [comment]
ok, the diff is not yet implemented will look at it if i can do something about it

Regards

Juneed

**Comment by juneedahamed** [comment]
Just provided support for bringing up the changes. 
Ctrl-k at log output
-vcnoparse option for VCStatus, VCDiff

Hope that helps
