### ISSUE TITLE
How to prevent stripping blank lines in svn commits?

### ISSUE THREAD

**Issue by idbrii** [juneedahamed/vc.vim#9]
When submitting to svn with VCCommit, I intentionally insert blank lines to organize my commit message. vc.vim strips out these blank lines. Is there a way to prevent this behavior?

on 9ce6e27

**Comment by juneedahamed** [comment]
Added new settings g:vc_commit_allow_blank_lines  set in .vimrc to 1 or help g:vc_commit_allow_blank_lines

**Comment by idbrii** [comment]
Thanks it works great!
